In [3]:
import pandas as pd
import numpy as np
import torch

In [4]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cpu device


In [20]:
t = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [21]:
t = t.to(torch.float32)

In [31]:
t = t.view(4,3)
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [36]:
t.to('cuda')

AssertionError: Torch not compiled with CUDA enabled

In [37]:
t.T

tensor([[ 1.,  4.,  7., 10.],
        [ 2.,  5.,  8., 11.],
        [ 3.,  6.,  9., 12.]])

In [53]:
# matrix multiplication 
a = torch.tensor([[1,2],[4,5]])
b = torch.tensor([[3,11],[3,5]])
print(torch.matmul(a,b))
print(a@b)
print(a*b)
print(b.matmul(a))

tensor([[ 9, 21],
        [27, 69]])
tensor([[ 9, 21],
        [27, 69]])
tensor([[ 3, 22],
        [12, 25]])
tensor([[47, 61],
        [23, 31]])
