In [16]:
import torch

In [17]:
def python_vanila(X, W, b):
  output = b
  for x, w in zip(X, W):
    output += x * w
    
  
  return output

In [18]:
import random
X = [random.random() for _ in range(100000)]
W = [random.random() for _ in range(100000)]
b = random.random()

In [19]:
%timeit python_vanila(X, W, b)

8.71 ms ± 2.82 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
def pytorch_version(X, W, b):
  return X.dot(W) + b

In [21]:
t_X = torch.tensor(X)
t_W = torch.tensor(W)
t_b = torch.tensor(b)

In [22]:
%timeit pytorch_version(t_X, t_W, t_b)

21.2 µs ± 480 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [23]:
print(python_vanila(X, W, b))
print(pytorch_version(t_X, t_W, t_b))


24882.618104221558
tensor(24882.6133)


Result is the same but it is way faster

### Now let's see a matrix by a vector multiplication

In [25]:
def python_matrix(X, w, b):
  result = []
  for x in X:
    output = b
    for x_j, w_j in zip(x, w):
      output += x_j * w_j
      result.append(output)
  
  return result

In [33]:
X = [[random.random() for _ in range(1000)] for _ in range(500)]
w = [random.random() for _ in range(1000)]
b = random.random()

In [34]:
%timeit python_matrix(X, w, b)

58.8 ms ± 1.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [43]:
def pytorch_matrix(X, w, b):
  return X.matmul(w) + b

In [44]:
t_X = torch.tensor(X)
t_w = torch.tensor(w)
t_b = torch.tensor(b)

In [45]:
%timeit pytorch_matrix(t_X, t_w, t_b)

74.9 µs ± 10.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


This is crazy how fast is this! bro what the fuck

# Now let's see matrix by matrix multiplication

In [46]:
def python_matrix_mul(X, W):
  output = [[0]*len(W[0]) for _ in range(len(X))]
  for i in range(len(W[0])):
    for k in range(len(X)):
      res = 0
      for j in range(len(W)):
        res += X[k][j] * W[j][i]
      output[k][i] = res

  return output

In [72]:
X = [[1,11], [30,4]]
W = [[7,2], [-2,4]]
python_matrix_mul(X, W)

[[-15, 46], [202, 76]]

In [50]:
torch.tensor(X).matmul(torch.tensor(W))

tensor([[-15,  46],
        [202,  76]])

In [75]:
X = [[random.random() for _ in range(100)] for _ in range(100)]
W = [[random.random() for _ in range(100)] for _ in range(100)]

In [68]:
%timeit python_matrix_mul(X, W)

1.43 s ± 461 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [76]:
t_X = torch.tensor(X)
t_W = torch.tensor(W)

In [70]:
%timeit t_X.matmul(t_W)

397 µs ± 8.69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [79]:
res = python_matrix_mul(X,W)
print(torch.tensor(res))
print(t_X.matmul(t_W))
torch.tensor(res) == t_X.matmul(t_W)

tensor([[26.2344, 26.6297, 25.6764,  ..., 24.0315, 24.5508, 25.8849],
        [24.6449, 28.0791, 26.7169,  ..., 24.6699, 26.5424, 26.8078],
        [25.4025, 26.7122, 28.2863,  ..., 26.3889, 27.7417, 25.4674],
        ...,
        [21.6980, 23.7485, 23.6584,  ..., 21.0976, 23.7496, 22.6124],
        [20.9818, 21.3759, 23.2836,  ..., 21.4318, 22.8028, 19.7733],
        [25.9496, 26.4271, 27.3356,  ..., 23.8985, 26.7330, 25.4176]])
tensor([[26.2344, 26.6297, 25.6764,  ..., 24.0315, 24.5508, 25.8849],
        [24.6449, 28.0791, 26.7169,  ..., 24.6699, 26.5424, 26.8078],
        [25.4025, 26.7122, 28.2863,  ..., 26.3889, 27.7417, 25.4674],
        ...,
        [21.6980, 23.7485, 23.6584,  ..., 21.0976, 23.7496, 22.6124],
        [20.9818, 21.3759, 23.2836,  ..., 21.4318, 22.8028, 19.7733],
        [25.9496, 26.4271, 27.3356,  ..., 23.8985, 26.7330, 25.4176]])


tensor([[False, False, False,  ...,  True, False,  True],
        [False,  True, False,  ..., False, False, False],
        [ True, False, False,  ..., False, False, False],
        ...,
        [False,  True,  True,  ..., False, False,  True],
        [ True,  True, False,  ..., False, False,  True],
        [False,  True, False,  ...,  True,  True, False]])